# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYxp5samJ11t52vIyr_YCWq_mKHmeu9-
"""

import numpy as np

from google.colab import files
drive.mount('/content/drive')
import os
path=r"/content/drive/MyDrive/"

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('animes.csv', low_memory=False)

columns=['uid','title','genre','score']
pd.set_option('display.max_columns', 9)
print(df[columns])

df.shape

df.groupby('title')['score'].mean().sort_values(ascending=False).head()

a=pd.DataFrame(df.groupby('title')['score'].mean())
a

df.dropna(inplace=True)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('dark')
# %matplotlib inline

plt.figure(figsize=(8,6))
plt.rcParams['patch.force_edgecolor'] = True
a['score'].hist(bins=50)

"""# Новый раздел"""

m=
q_movies = df.copy().loc[df['score'] >= m]
q_movies.shape

bruh=['uid','title','score']
print(df[bruh])

df[df['score'] > 5]
df.sample(frac=0.25)